# Generated by Django 5.2.7 on 2025-10-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='posted_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
    ]
